/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ApiAdminDocsRouteImport } from './routes/api-admin/docs'
import { Route as ApiAdminKeysRouteImport } from './routes/api-admin/keys'
import { Route as ApiAdminUsageRouteImport } from './routes/api-admin/usage'
import { Route as CollectJobsRouteImport } from './routes/collect/jobs'
import { Route as CollectManualRouteImport } from './routes/collect/manual'
import { Route as CollectSchedulesRouteImport } from './routes/collect/schedules'
import { Route as MasterDatasetsRouteImport } from './routes/master/datasets'
import { Route as MasterProvidersRouteImport } from './routes/master/providers'
import { Route as MasterStationsRouteImport } from './routes/master/stations'
import { Route as SystemHealthRouteImport } from './routes/system/health'
import { Route as SystemLogsRouteImport } from './routes/system/logs'
import { Route as WeatherDailyRouteImport } from './routes/weather/daily'
import { Route as WeatherDownloadRouteImport } from './routes/weather/download'
import { Route as WeatherGapsRouteImport } from './routes/weather/gaps'
import { Route as WeatherHourlyRouteImport } from './routes/weather/hourly'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1WeatherDailyRouteImport } from './routes/api/v1/weather/daily'
import { Route as ApiV1WeatherHourlyRouteImport } from './routes/api/v1/weather/hourly'
import { Route as ApiV1WeatherStationsRouteImport } from './routes/api/v1/weather/stations'
import { Route as ApiV1WeatherSummaryRouteImport } from './routes/api/v1/weather/summary'
import { Route as ApiV1WeatherHourlyNearestRouteImport } from './routes/api/v1/weather/hourly/nearest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDocsRoute = ApiAdminDocsRouteImport.update({
  id: '/api-admin/docs',
  path: '/api-admin/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminKeysRoute = ApiAdminKeysRouteImport.update({
  id: '/api-admin/keys',
  path: '/api-admin/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsageRoute = ApiAdminUsageRouteImport.update({
  id: '/api-admin/usage',
  path: '/api-admin/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectJobsRoute = CollectJobsRouteImport.update({
  id: '/collect/jobs',
  path: '/collect/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectManualRoute = CollectManualRouteImport.update({
  id: '/collect/manual',
  path: '/collect/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectSchedulesRoute = CollectSchedulesRouteImport.update({
  id: '/collect/schedules',
  path: '/collect/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDatasetsRoute = MasterDatasetsRouteImport.update({
  id: '/master/datasets',
  path: '/master/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterProvidersRoute = MasterProvidersRouteImport.update({
  id: '/master/providers',
  path: '/master/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterStationsRoute = MasterStationsRouteImport.update({
  id: '/master/stations',
  path: '/master/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemHealthRoute = SystemHealthRouteImport.update({
  id: '/system/health',
  path: '/system/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemLogsRoute = SystemLogsRouteImport.update({
  id: '/system/logs',
  path: '/system/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherDailyRoute = WeatherDailyRouteImport.update({
  id: '/weather/daily',
  path: '/weather/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherDownloadRoute = WeatherDownloadRouteImport.update({
  id: '/weather/download',
  path: '/weather/download',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherGapsRoute = WeatherGapsRouteImport.update({
  id: '/weather/gaps',
  path: '/weather/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherHourlyRoute = WeatherHourlyRouteImport.update({
  id: '/weather/hourly',
  path: '/weather/hourly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WeatherDailyRoute = ApiV1WeatherDailyRouteImport.update({
  id: '/api/v1/weather/daily',
  path: '/api/v1/weather/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WeatherHourlyRoute = ApiV1WeatherHourlyRouteImport.update({
  id: '/api/v1/weather/hourly',
  path: '/api/v1/weather/hourly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WeatherStationsRoute = ApiV1WeatherStationsRouteImport.update({
  id: '/api/v1/weather/stations',
  path: '/api/v1/weather/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WeatherSummaryRoute = ApiV1WeatherSummaryRouteImport.update({
  id: '/api/v1/weather/summary',
  path: '/api/v1/weather/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WeatherHourlyNearestRoute =
  ApiV1WeatherHourlyNearestRouteImport.update({
    id: '/nearest',
    path: '/nearest',
    getParentRoute: () => ApiV1WeatherHourlyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/api-admin/docs': typeof ApiAdminDocsRoute
  '/api-admin/keys': typeof ApiAdminKeysRoute
  '/api-admin/usage': typeof ApiAdminUsageRoute
  '/collect/jobs': typeof CollectJobsRoute
  '/collect/manual': typeof CollectManualRoute
  '/collect/schedules': typeof CollectSchedulesRoute
  '/master/datasets': typeof MasterDatasetsRoute
  '/master/providers': typeof MasterProvidersRoute
  '/master/stations': typeof MasterStationsRoute
  '/system/health': typeof SystemHealthRoute
  '/system/logs': typeof SystemLogsRoute
  '/weather/daily': typeof WeatherDailyRoute
  '/weather/download': typeof WeatherDownloadRoute
  '/weather/gaps': typeof WeatherGapsRoute
  '/weather/hourly': typeof WeatherHourlyRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/weather/daily': typeof ApiV1WeatherDailyRoute
  '/api/v1/weather/hourly': typeof ApiV1WeatherHourlyRouteWithChildren
  '/api/v1/weather/stations': typeof ApiV1WeatherStationsRoute
  '/api/v1/weather/summary': typeof ApiV1WeatherSummaryRoute
  '/api/v1/weather/hourly/nearest': typeof ApiV1WeatherHourlyNearestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/api-admin/docs': typeof ApiAdminDocsRoute
  '/api-admin/keys': typeof ApiAdminKeysRoute
  '/api-admin/usage': typeof ApiAdminUsageRoute
  '/collect/jobs': typeof CollectJobsRoute
  '/collect/manual': typeof CollectManualRoute
  '/collect/schedules': typeof CollectSchedulesRoute
  '/master/datasets': typeof MasterDatasetsRoute
  '/master/providers': typeof MasterProvidersRoute
  '/master/stations': typeof MasterStationsRoute
  '/system/health': typeof SystemHealthRoute
  '/system/logs': typeof SystemLogsRoute
  '/weather/daily': typeof WeatherDailyRoute
  '/weather/download': typeof WeatherDownloadRoute
  '/weather/gaps': typeof WeatherGapsRoute
  '/weather/hourly': typeof WeatherHourlyRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/weather/daily': typeof ApiV1WeatherDailyRoute
  '/api/v1/weather/hourly': typeof ApiV1WeatherHourlyRouteWithChildren
  '/api/v1/weather/stations': typeof ApiV1WeatherStationsRoute
  '/api/v1/weather/summary': typeof ApiV1WeatherSummaryRoute
  '/api/v1/weather/hourly/nearest': typeof ApiV1WeatherHourlyNearestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/api-admin/docs': typeof ApiAdminDocsRoute
  '/api-admin/keys': typeof ApiAdminKeysRoute
  '/api-admin/usage': typeof ApiAdminUsageRoute
  '/collect/jobs': typeof CollectJobsRoute
  '/collect/manual': typeof CollectManualRoute
  '/collect/schedules': typeof CollectSchedulesRoute
  '/master/datasets': typeof MasterDatasetsRoute
  '/master/providers': typeof MasterProvidersRoute
  '/master/stations': typeof MasterStationsRoute
  '/system/health': typeof SystemHealthRoute
  '/system/logs': typeof SystemLogsRoute
  '/weather/daily': typeof WeatherDailyRoute
  '/weather/download': typeof WeatherDownloadRoute
  '/weather/gaps': typeof WeatherGapsRoute
  '/weather/hourly': typeof WeatherHourlyRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/weather/daily': typeof ApiV1WeatherDailyRoute
  '/api/v1/weather/hourly': typeof ApiV1WeatherHourlyRouteWithChildren
  '/api/v1/weather/stations': typeof ApiV1WeatherStationsRoute
  '/api/v1/weather/summary': typeof ApiV1WeatherSummaryRoute
  '/api/v1/weather/hourly/nearest': typeof ApiV1WeatherHourlyNearestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/api-admin/docs'
    | '/api-admin/keys'
    | '/api-admin/usage'
    | '/collect/jobs'
    | '/collect/manual'
    | '/collect/schedules'
    | '/master/datasets'
    | '/master/providers'
    | '/master/stations'
    | '/system/health'
    | '/system/logs'
    | '/weather/daily'
    | '/weather/download'
    | '/weather/gaps'
    | '/weather/hourly'
    | '/api/v1/health'
    | '/api/v1/weather/daily'
    | '/api/v1/weather/hourly'
    | '/api/v1/weather/stations'
    | '/api/v1/weather/summary'
    | '/api/v1/weather/hourly/nearest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/api-admin/docs'
    | '/api-admin/keys'
    | '/api-admin/usage'
    | '/collect/jobs'
    | '/collect/manual'
    | '/collect/schedules'
    | '/master/datasets'
    | '/master/providers'
    | '/master/stations'
    | '/system/health'
    | '/system/logs'
    | '/weather/daily'
    | '/weather/download'
    | '/weather/gaps'
    | '/weather/hourly'
    | '/api/v1/health'
    | '/api/v1/weather/daily'
    | '/api/v1/weather/hourly'
    | '/api/v1/weather/stations'
    | '/api/v1/weather/summary'
    | '/api/v1/weather/hourly/nearest'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/api-admin/docs'
    | '/api-admin/keys'
    | '/api-admin/usage'
    | '/collect/jobs'
    | '/collect/manual'
    | '/collect/schedules'
    | '/master/datasets'
    | '/master/providers'
    | '/master/stations'
    | '/system/health'
    | '/system/logs'
    | '/weather/daily'
    | '/weather/download'
    | '/weather/gaps'
    | '/weather/hourly'
    | '/api/v1/health'
    | '/api/v1/weather/daily'
    | '/api/v1/weather/hourly'
    | '/api/v1/weather/stations'
    | '/api/v1/weather/summary'
    | '/api/v1/weather/hourly/nearest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  ApiAdminDocsRoute: typeof ApiAdminDocsRoute
  ApiAdminKeysRoute: typeof ApiAdminKeysRoute
  ApiAdminUsageRoute: typeof ApiAdminUsageRoute
  CollectJobsRoute: typeof CollectJobsRoute
  CollectManualRoute: typeof CollectManualRoute
  CollectSchedulesRoute: typeof CollectSchedulesRoute
  MasterDatasetsRoute: typeof MasterDatasetsRoute
  MasterProvidersRoute: typeof MasterProvidersRoute
  MasterStationsRoute: typeof MasterStationsRoute
  SystemHealthRoute: typeof SystemHealthRoute
  SystemLogsRoute: typeof SystemLogsRoute
  WeatherDailyRoute: typeof WeatherDailyRoute
  WeatherDownloadRoute: typeof WeatherDownloadRoute
  WeatherGapsRoute: typeof WeatherGapsRoute
  WeatherHourlyRoute: typeof WeatherHourlyRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1WeatherDailyRoute: typeof ApiV1WeatherDailyRoute
  ApiV1WeatherHourlyRoute: typeof ApiV1WeatherHourlyRouteWithChildren
  ApiV1WeatherStationsRoute: typeof ApiV1WeatherStationsRoute
  ApiV1WeatherSummaryRoute: typeof ApiV1WeatherSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-admin/docs': {
      id: '/api-admin/docs'
      path: '/api-admin/docs'
      fullPath: '/api-admin/docs'
      preLoaderRoute: typeof ApiAdminDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-admin/keys': {
      id: '/api-admin/keys'
      path: '/api-admin/keys'
      fullPath: '/api-admin/keys'
      preLoaderRoute: typeof ApiAdminKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-admin/usage': {
      id: '/api-admin/usage'
      path: '/api-admin/usage'
      fullPath: '/api-admin/usage'
      preLoaderRoute: typeof ApiAdminUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collect/jobs': {
      id: '/collect/jobs'
      path: '/collect/jobs'
      fullPath: '/collect/jobs'
      preLoaderRoute: typeof CollectJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collect/manual': {
      id: '/collect/manual'
      path: '/collect/manual'
      fullPath: '/collect/manual'
      preLoaderRoute: typeof CollectManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collect/schedules': {
      id: '/collect/schedules'
      path: '/collect/schedules'
      fullPath: '/collect/schedules'
      preLoaderRoute: typeof CollectSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/datasets': {
      id: '/master/datasets'
      path: '/master/datasets'
      fullPath: '/master/datasets'
      preLoaderRoute: typeof MasterDatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/providers': {
      id: '/master/providers'
      path: '/master/providers'
      fullPath: '/master/providers'
      preLoaderRoute: typeof MasterProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/stations': {
      id: '/master/stations'
      path: '/master/stations'
      fullPath: '/master/stations'
      preLoaderRoute: typeof MasterStationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/health': {
      id: '/system/health'
      path: '/system/health'
      fullPath: '/system/health'
      preLoaderRoute: typeof SystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/logs': {
      id: '/system/logs'
      path: '/system/logs'
      fullPath: '/system/logs'
      preLoaderRoute: typeof SystemLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/daily': {
      id: '/weather/daily'
      path: '/weather/daily'
      fullPath: '/weather/daily'
      preLoaderRoute: typeof WeatherDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/download': {
      id: '/weather/download'
      path: '/weather/download'
      fullPath: '/weather/download'
      preLoaderRoute: typeof WeatherDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/gaps': {
      id: '/weather/gaps'
      path: '/weather/gaps'
      fullPath: '/weather/gaps'
      preLoaderRoute: typeof WeatherGapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/hourly': {
      id: '/weather/hourly'
      path: '/weather/hourly'
      fullPath: '/weather/hourly'
      preLoaderRoute: typeof WeatherHourlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/weather/daily': {
      id: '/api/v1/weather/daily'
      path: '/api/v1/weather/daily'
      fullPath: '/api/v1/weather/daily'
      preLoaderRoute: typeof ApiV1WeatherDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/weather/hourly': {
      id: '/api/v1/weather/hourly'
      path: '/api/v1/weather/hourly'
      fullPath: '/api/v1/weather/hourly'
      preLoaderRoute: typeof ApiV1WeatherHourlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/weather/stations': {
      id: '/api/v1/weather/stations'
      path: '/api/v1/weather/stations'
      fullPath: '/api/v1/weather/stations'
      preLoaderRoute: typeof ApiV1WeatherStationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/weather/summary': {
      id: '/api/v1/weather/summary'
      path: '/api/v1/weather/summary'
      fullPath: '/api/v1/weather/summary'
      preLoaderRoute: typeof ApiV1WeatherSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/weather/hourly/nearest': {
      id: '/api/v1/weather/hourly/nearest'
      path: '/nearest'
      fullPath: '/api/v1/weather/hourly/nearest'
      preLoaderRoute: typeof ApiV1WeatherHourlyNearestRouteImport
      parentRoute: typeof ApiV1WeatherHourlyRoute
    }
  }
}

interface ApiV1WeatherHourlyRouteChildren {
  ApiV1WeatherHourlyNearestRoute: typeof ApiV1WeatherHourlyNearestRoute
}

const ApiV1WeatherHourlyRouteChildren: ApiV1WeatherHourlyRouteChildren = {
  ApiV1WeatherHourlyNearestRoute: ApiV1WeatherHourlyNearestRoute,
}

const ApiV1WeatherHourlyRouteWithChildren =
  ApiV1WeatherHourlyRoute._addFileChildren(ApiV1WeatherHourlyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  ApiAdminDocsRoute: ApiAdminDocsRoute,
  ApiAdminKeysRoute: ApiAdminKeysRoute,
  ApiAdminUsageRoute: ApiAdminUsageRoute,
  CollectJobsRoute: CollectJobsRoute,
  CollectManualRoute: CollectManualRoute,
  CollectSchedulesRoute: CollectSchedulesRoute,
  MasterDatasetsRoute: MasterDatasetsRoute,
  MasterProvidersRoute: MasterProvidersRoute,
  MasterStationsRoute: MasterStationsRoute,
  SystemHealthRoute: SystemHealthRoute,
  SystemLogsRoute: SystemLogsRoute,
  WeatherDailyRoute: WeatherDailyRoute,
  WeatherDownloadRoute: WeatherDownloadRoute,
  WeatherGapsRoute: WeatherGapsRoute,
  WeatherHourlyRoute: WeatherHourlyRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1WeatherDailyRoute: ApiV1WeatherDailyRoute,
  ApiV1WeatherHourlyRoute: ApiV1WeatherHourlyRouteWithChildren,
  ApiV1WeatherStationsRoute: ApiV1WeatherStationsRoute,
  ApiV1WeatherSummaryRoute: ApiV1WeatherSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
